version: '3.0'

services:
  web:
    image: projeto-b2
    privileged: true 
    container_name: projeto-b2
    volumes:
      - ./:/projeto/

    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["sleep","infinity"]